# -*- coding: utf-8 -*-
"""Assignment_02_Coursework_OptionB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SC40m-m8mXqABkmDLx2iLfVZ2BUtlqOt

# CCS3440 – Artificial Intelligence Coursework
## Selected Task: Option B – Patient Readmission Prediction
**Student ID:** 23UG1-0018, 23UG1-0151, 23UG1-0072, 23UG1-0069, CIT-23-02-0091

## Task 01 – Problem Definition and Literature Review

### 1. Problem Definition
The objective of this prediction task is to determine whether a discharged hospital inpatient will be readmitted to the hospital within 30 days of discharge (`readmitted_30_days`). This is formulated as a **binary classification** problem where:
- **Target variable (`readmitted_30_days`):**
  - `1` = Patient is readmitted within 30 days of discharge.
  - `0` = Patient is not readmitted.

*Target Cohort Definition:* The analysis is strictly restricted to discharged inpatients (`admitted == 1`). Outpatients (`admitted == 0`) are excluded from readmission risk modeling because outpatients have zero hospital stays and zero readmission events by definition. Including outpatients introduces trivial target correlation and data leakage where admission status dominates prediction rather than actual clinical risk factors.

### 2. Significance
Patient readmission within a short timeframe is a critical indicator of healthcare quality and operational efficiency:
- **Quality of Care:** High readmission rates often reflect suboptimal inpatient care, premature discharges, or inadequate post-discharge transitional care.
- **Financial Impact:** Unplanned readmissions result in significant unnecessary financial costs for healthcare providers and patients.
- **Resource Allocation:** Predicting hospital readmission risk allows clinicians to target high-risk patients with intensive follow-up care, reducing overall readmission rates and optimizing hospital bed capacity.

### 3. Literature Review (5 Peer-Reviewed Research Papers)
Clinical readmission modeling has been widely explored in artificial intelligence and health informatics literature:
- **Paper 1: Deep Learning on EHRs (Rajkomar et al., 2018):** In *"Scalable and accurate deep learning with electronic health records"* (npj Digital Medicine) [1], the authors demonstrated that deep learning models (recurrent neural networks and feedforward networks) can ingest raw clinical records represented in the FHIR standard, yielding AUROCs for 30-day readmissions between 0.75–0.76. This highlighted that deep models capture complex temporal dependencies without site-specific manual feature engineering.
- **Paper 2: Traditional Risk Prediction Models (Kansagara et al., 2011):** In *"Risk prediction models for hospital readmission: a systematic review"* (JAMA) [2], Kansagara et al. reviewed 26 unique readmission prediction models (including the LACE index). They concluded that traditional administrative-data models performed poorly (c-statistic 0.55–0.65) and highlighted that clinical, social, and functional variables are rarely integrated, leading to poor model generalizability.
- **Paper 3: Explainable AI in Medicine (Lundberg & Lee, 2017):** In *"A unified approach to interpreting model predictions"* (NeurIPS) [3], the authors introduced SHAP (Shapley Additive exPlanations). They proved that Shapley values provide the only consistent and locally accurate additive feature attribution method for complex black-box models, which is essential to gain clinical trust before deploying AI in healthcare settings.
- **Paper 4: Intelligible Healthcare Classifiers (Caruana et al., 2015):** In *"Intelligible models for healthcare: predicting pneumonia risk and hospital 30-day readmission"* (KDD) [4], the authors showed that Generalized Additive Models (GAMs) can achieve high accuracy while remaining completely interpretable. They highlighted a famous case study where a neural network erroneously classified asthmatic pneumonia patients as low-risk due to a correlation in the data (asthmatics were directly admitted to the ICU, which improved their outcomes, but the model interpreted asthmatic status as protective).
- **Paper 5: Clinical Predictor Methodologies (Amarasingham et al., 2010):** In *"Clinical predictor methodology (CPM) for readmission: a systematic approach"* (Medical Care) [5], the authors demonstrated that combining electronic medical record variables with social barriers significantly improves readmission classification accuracy compared to using billing codes alone.

### 4. Research Gaps & Proposed Approach
A review of existing clinical readmission modeling highlights three key research gaps:
1. **The Interpretability Tradeoff:** Advanced deep learning models (e.g., npj Digital Medicine [1]) achieve high scores but act as black boxes, making them difficult for clinicians to trust at the bedside. Conversely, simple scores (e.g., LACE [2]) yield low predictive accuracy (c-statistic 0.55-0.65). We bridge this gap by deploying a GridSearch-tuned Random Forest ensemble backed by global Permutation Importance and local SHAP attributions (Lundberg & Lee [3]).
2. **Evaluation Rigor & Socioeconomic Bias:** Simple 80:20 train-test splits can suffer from evaluation variance or data leakage. We address this gap by evaluating all models using **Stratified 5-Fold Cross-Validation**, with **nested GridSearchCV hyperparameter tuning for Random Forest**, comparing the **Baseline Full Dataset Cohort ($N=1000$)** and the **Refined Discharged Inpatient Cohort ($N=330$)**, encapsulating scaling, encoding, and feature selection inside leakage-free pipelines, and evaluating demographic subgroup performance across gender and age.
3. **Lack of Direct Clinical Translation:** Academic studies rarely validate their models through bedside prototype interfaces. We bridge this gap by building a bedside Streamlit calculator with integrated operational constraint checks to translate predictions into clinical workflow support.

# Task 02 – Dataset Ingestion & Understanding

We import the required libraries, configure reproducibility parameters, ingest the `smartcare_ai_dataset_1000.csv` dataset, inspect both the raw full dataset ($N=1000$) and the restricted inpatient cohort (`admitted == 1`, $N=330$), load the data dictionary, and examine the structure.
"""

# Imports and reproducibility configuration
import json
import warnings
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import shap

from IPython.display import display

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    RocCurveDisplay
)
from sklearn.model_selection import (
    GridSearchCV,
    StratifiedKFold,
    cross_val_predict,
    cross_val_score,
    cross_validate,
    train_test_split
)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

warnings.filterwarnings("ignore")

RANDOM_STATE = 42
TARGET = "readmitted_30_days"
DATA_FILE = "smartcare_ai_dataset_1000.csv"
DICTIONARY_FILE = "smartcare_ai_dataset_data_dictionary.csv"

np.random.seed(RANDOM_STATE)
sns.set_theme(style="whitegrid")

# Trigger the interactive file gateway to upload local CSV (for Google Colab)
try:
    from google.colab import files
    print("Colab environment detected. Triggering file upload widget:")
    uploaded = files.upload()
except ImportError:
    print("Non-Colab environment. Proceeding with local dataset files.")

# Ingest raw dataset
raw_df = pd.read_csv(DATA_FILE)
print("\nSmartCare raw dataset loaded successfully!")
print(f"Raw Dataset Dimension: {raw_df.shape[0]} rows, {raw_df.shape[1]} columns")

# Restrict cohort to discharged inpatients (admitted == 1) to model true clinical risk
df = raw_df[raw_df['admitted'] == 1].copy().reset_index(drop=True)
print(f"\nCohort Filtering: Restricted analysis to discharged inpatients (admitted == 1).")
print(f"Inpatient Cohort Dimension: {df.shape[0]} rows, {df.shape[1]} columns")

# Load and display the data dictionary for structural understanding
data_dict = pd.read_csv(DICTIONARY_FILE)
print("\n--- Data Dictionary Overview ---")
display(data_dict)

"""### Data Dictionary Interpretation

The provided data dictionary contains all 33 original dataset attributes and their meanings. For this Option B task:
- **Target variable:** `readmitted_30_days` (`1 = Readmitted`, `0 = Not Readmitted`).
- **Main input groups:** demographic (`age`, `gender`, `blood_group`), hospital/appointment history, admission and stay information, clinical measurements, treatment/laboratory counts, and billing/payment information.
- **Columns excluded from model inputs:** identifiers (`record_id`, `patient_id`), date (`appointment_date`), targets belonging to other coursework options (`no_show`, `disease_risk_level`), and `admitted` after the inpatient cohort is fixed.

The complete attribute names and descriptions are displayed from `smartcare_ai_dataset_data_dictionary.csv` above.

Display the first few rows of the inpatient dataset to verify structure and content.
"""

# Display the first 5 records of the inpatient cohort
df.head()

"""Analyze the data types, non-null values, and summary statistics of numeric columns in the inpatient cohort."""

# Check dataset info for data types and non-null values
print("--- Inpatient Dataset Information ---")
df.info()

# Show descriptive summary statistics for numerical attributes
print("\n--- Descriptive Statistics Summary (Inpatient Cohort) ---")
display(df.describe().T)

"""Assess the target variable balance. First show the full dataset counts, then show the inpatient cohort counts used for the model."""

# Check target variable distribution in the full dataset
print("\nReadmission counts in the full dataset:")
readmission_counts = raw_df[TARGET].value_counts().sort_index()
print(f"Not readmitted within 30 days: {readmission_counts.get(0, 0)}")
print(f"Readmitted within 30 days: {readmission_counts.get(1, 0)}")

print("\nTarget variable percentage distribution (Full Dataset):")
print(raw_df[TARGET].value_counts(normalize=True).sort_index() * 100)

# Check target variable distribution for discharged inpatients used for the model
print("\nTarget variable 'readmitted_30_days' frequency counts (Inpatient Cohort):")
print(df[TARGET].value_counts())
print("\nTarget variable percentage distribution (Inpatient Cohort):")
print(df[TARGET].value_counts(normalize=True) * 100)

"""# Task 03 – Data Preprocessing & Feature Engineering

### Preprocessing & Data Cleaning Decisions:

1. **Cohort Selection (Leakage Prevention):** Filtering to `admitted == 1` eliminates the constant outpatient zero-readmission bias.
2. **Missing Value Handling:** In both cohorts, missing `room_type` values are imputed with `'None'` (representing Unknown/Unassigned) to prevent data deletion.
3. **Duplicate Record Detection:** Zero duplicate rows were found in the dataset, confirming data integrity.
4. **Outlier Identification:** An IQR analysis is performed on numerical features (`age`, `length_of_stay_days`, `total_bill_lkr`, `bmi`). Severe cases (long stays, high bills) represent critical clinical ICU events and are retained to preserve high-risk indicators.
5. **Feature Leakage Prevention:** Identifiers (`record_id`, `patient_id`), appointment dates, non-relevant targets (`no_show`, `disease_risk_level`), and `admitted` (which is constant `1` for all inpatients) are dropped from predictors.
6. **Feature Engineering:** Three clinical/operational metrics are constructed:
   - `pulse_pressure`: Difference between systolic and diastolic blood pressure (`systolic_bp - diastolic_bp`).
   - `missed_ratio`: Ratio of missed appointments (`missed_previous_appointments / (previous_appointments + 1)`).
   - `charge_per_day`: Charges relative to length of stay (`total_bill_lkr / (length_of_stay_days + 1)`).
7. **Encapsulated Preprocessing & Feature Selection:** Numerical scaling with `StandardScaler`, categorical encoding with `OneHotEncoder(drop='first', handle_unknown='ignore')`, and `SelectPercentile` feature selection are fitted inside each scikit-learn model `Pipeline`. The three engineered features are calculated before the pipeline because they use only predictor values and not the target.
8. **Rigorous Evaluation Strategy:** We use **Stratified 5-Fold Cross-Validation** across the inpatient cohort ($N=330$).
   - **Outer 5-Fold Stratified CV:** Evaluates all three coursework models and generates out-of-fold Accuracy, Precision, Recall, F1-Score, ROC-AUC, and confusion-matrix results.
   - **Inner 5-Fold Stratified CV inside GridSearchCV:** Used only for the Random Forest to select `max_depth` and `n_estimators` without using the outer validation fold.

"""

# Check missing values in inpatient cohort
print("Missing Values in Inpatient Cohort:")
missing = df.isnull().sum()
print(missing[missing > 0])

# Handle missing values in 'room_type' by replacing NaN with 'None'
df['room_type'] = df['room_type'].fillna('None')
raw_df['room_type'] = raw_df['room_type'].fillna('None')

# Verify zero remaining missing values
total_missing = df.isnull().sum().sum()
print(f"Total remaining missing values: {total_missing}")

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Identify outliers using IQR method for key numerical features
num_check_cols = ['age', 'length_of_stay_days', 'total_bill_lkr', 'bmi']
print("\n--- Outlier Detection Analysis (IQR Method - Inpatients) ---")
for col in num_check_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers_count = df[(df[col] < lower_bound) | (df[col] > upper_bound)].shape[0]
    print(f"Feature: {col:<20} | Q1: {Q1:<6.1f} | Q3: {Q3:<6.1f} | IQR: {IQR:<6.1f} | Outliers: {outliers_count}")

# Create engineered clinical features for inpatient cohort
df['pulse_pressure'] = df['systolic_bp'] - df['diastolic_bp']
df['missed_ratio'] = df['missed_previous_appointments'] / (df['previous_appointments'] + 1)
df['charge_per_day'] = df['total_bill_lkr'] / (df['length_of_stay_days'] + 1)

# Create engineered clinical features for raw full dataset (for Baseline comparison)
raw_df['pulse_pressure'] = raw_df['systolic_bp'] - raw_df['diastolic_bp']
raw_df['missed_ratio'] = raw_df['missed_previous_appointments'] / (raw_df['previous_appointments'] + 1)
raw_df['charge_per_day'] = raw_df['total_bill_lkr'] / (raw_df['length_of_stay_days'] + 1)

print("\nEngineered features successfully created. Sample records:")
display(df[['pulse_pressure', 'missed_ratio', 'charge_per_day']].head())

# Drop identifiers, non-relevant targets, and constant 'admitted' feature
drop_columns = ['record_id', 'patient_id', 'appointment_date', 'no_show', 'disease_risk_level', 'admitted', TARGET]

X = df.drop(columns=drop_columns)
y = df[TARGET]

print(f"\nPredictors matrix shape X: {X.shape}")
print(f"Target vector shape y: {y.shape}")

# Categorize predictors into numerical and categorical subgroups
num_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = X.select_dtypes(include=['object', 'string']).columns.tolist()

print(f"Numerical columns for scaling: {num_cols}")
print(f"Categorical columns for encoding: {cat_cols}")

# Build ColumnTransformer: scale numerical values, one-hot encode categoricals
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False), cat_cols)
    ]
)

print("ColumnTransformer preprocessor established successfully.")

"""### Feature Selection & Preprocessing Verification inside Pipeline"""

# Fit preprocessor on dataset to verify output dimensions and feature selection
X_preprocessed = preprocessor.fit_transform(X, y)
feature_names_out = preprocessor.get_feature_names_out()

selector = SelectPercentile(score_func=f_classif, percentile=80)
X_selected = selector.fit_transform(X_preprocessed, y)
selected_mask = selector.get_support()

selected_features = [feature_names_out[i] for i, sel in enumerate(selected_mask) if sel]
eliminated_features = [feature_names_out[i] for i, sel in enumerate(selected_mask) if not sel]

print(f"Feature Selection Complete: Selected {len(selected_features)} features out of {len(feature_names_out)} preprocessed features.")
print("\n--- Selected Features ---")
print(selected_features)
print("\n--- Eliminated Features ---")
print(eliminated_features)

"""# Task 04 – Exploratory Data Analysis (EDA)

We visualize class balances, attribute relationships, distributions, and correlation patterns within the inpatient cohort, displaying each plot figure individually one by one.

### Visual 1: Inpatient Readmission Target Distribution
"""

# Visual 1: Target Class Countplot
plt.figure(figsize=(6, 4))
sns.countplot(x=df[TARGET], hue=df[TARGET], palette='coolwarm', legend=False)
plt.title("Visual 1: Inpatient Readmission Count Distribution (0 = No, 1 = Yes)")
plt.xlabel("Readmission Status")
plt.ylabel("Inpatient Counts")
plt.show()

"""**EDA Insight 1:** The inpatient cohort contains 253 readmitted patients (76.7%) and 77 not-readmitted patients (23.3%). This shows a clear majority positive class, so stratified evaluation is important.

### Visual 2:Readmission Target Distribution - Full Dataset
"""

# Visual: Readmission Target Distribution - Full Dataset

# Plot
plt.figure(figsize=(6, 4))

sns.countplot(
    x=raw_df[TARGET],
    hue=raw_df[TARGET],
    palette='coolwarm',
    legend=False
)

plt.title("Full Dataset Readmission Count Distribution (0 = No, 1 = Yes)")
plt.xlabel("Readmission Status")
plt.ylabel("Patient Counts")

plt.show()

"""### Visual 2: Length of Stay (Days) by Readmission Status"""

# Visual 2: Boxplot comparing length of stay grouped by readmission status
plt.figure(figsize=(7, 4))
sns.boxplot(x=df[TARGET], y=df['length_of_stay_days'], hue=df[TARGET], palette='Set2', legend=False)
plt.title("Visual 2: Length of Stay (Days) by Readmission Status (Inpatient Cohort)")
plt.xlabel("Readmission Status (0 = No, 1 = Yes)")
plt.ylabel("Hospital Length of Stay (Days)")
plt.show()

"""**EDA Insight 2:** Both classes have a median stay of about 3 days, but the readmitted group has a slightly higher mean stay (3.48 days) than the not-readmitted group (2.88 days). The overlap shows that length of stay alone cannot separate the classes well.

### Visual 3: Patient Age Distribution Stratified by Readmission
"""

# Visual 3: Histogram showing age distributions stratified by target
plt.figure(figsize=(8, 5))
sns.histplot(data=df, x='age', hue=TARGET, multiple='stack', kde=True, palette='viridis', bins=20)
plt.title("Visual 3: Inpatient Age Distribution by Readmission Status")
plt.xlabel("Age (Years)")
plt.ylabel("Count")
plt.show()

"""**EDA Insight 3:** Readmitted patients are slightly older on average (45.79 years) than not-readmitted patients (39.22 years), but the distributions overlap considerably. Age therefore provides some signal but is not sufficient by itself.

### Visual 4: Relationship between Length of Stay and Total Bill Charges
"""

# Visual 4: Scatter Plot: Length of stay vs Total bill amount colored by readmission
plt.figure(figsize=(8, 5))
sns.scatterplot(
    x=df['length_of_stay_days'],
    y=df['total_bill_lkr'],
    hue=df[TARGET],
    palette='coolwarm',
    alpha=0.7,
    s=80
)
plt.title("Visual 4: Relationship: Hospital Stay vs Total Bill Charges (Inpatient Cohort)")
plt.xlabel("Length of Stay (Days)")
plt.ylabel("Total Bill (LKR)")
plt.legend(title="Readmitted")
plt.show()

"""**EDA Insight 4:** Length of stay and total bill have a modest positive correlation (approximately 0.22). Longer stays often have higher bills, but the wide spread indicates that other clinical and service factors also affect billing and readmission.

### Visual 5: Correlation Matrix Heatmap of Numerical Features
"""

# Visual 5: Heatmap showing correlation coefficients among numerical features and target
plt.figure(figsize=(12, 10))
numeric_cols_with_target = num_cols + [TARGET]
corr_matrix = df[numeric_cols_with_target].corr()

sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', vmin=-1, vmax=1, linewidths=0.5)
plt.title("Visual 5: Correlation Matrix of Numerical Features (Inpatient Cohort)")
plt.show()

"""**EDA Insight 5:** No single numerical variable has a strong linear correlation with readmission. The largest simple correlations with the target are still relatively small (for example, age about 0.17, previous admissions about 0.15, and length of stay about 0.14), supporting the use of multivariable machine learning models.

# Task 05 – Machine Learning Model Development & Stratified Cross-Validation

We train three machine learning classifiers (Decision Tree, K-Nearest Neighbors, and Random Forest). All three are evaluated using **Stratified 5-Fold Cross-Validation** across the inpatient cohort ($N=330$). The Random Forest is additionally tuned using **GridSearchCV inside each outer fold**, giving it a nested hyperparameter-tuning process.

### 1. Decision Tree Classifier
"""

# Decision Tree Pipeline
dt_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('selector', SelectPercentile(score_func=f_classif, percentile=80)),
    ('classifier', DecisionTreeClassifier(max_depth=5, random_state=RANDOM_STATE))
])

print("Decision Tree Pipeline Established.")

"""### 2. K-Nearest Neighbors (KNN) Classifier"""

# KNN Pipeline
knn_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('selector', SelectPercentile(score_func=f_classif, percentile=80)),
    ('classifier', KNeighborsClassifier(n_neighbors=5))
])

print("KNN Pipeline Established.")

"""### 3. Random Forest Classifier (GridSearchCV with Inner Stratified CV)

"""

# Random Forest Pipeline with GridSearch hyperparameter tuning
rf_clf = RandomForestClassifier(random_state=RANDOM_STATE)

rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('selector', SelectPercentile(score_func=f_classif, percentile=80)),
    ('classifier', rf_clf)
])

param_grid = {
    'classifier__n_estimators': [50, 100, 150],
    'classifier__max_depth': [4, 6, 8, 10]
}

# Inner CV for hyperparameter selection
inner_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
grid_search_rf = GridSearchCV(
    rf_pipeline,
    param_grid,
    cv=inner_cv,
    scoring='f1',
    n_jobs=1
)

print("GridSearchCV Random Forest Pipeline Established.")

"""# Task 06 – Model Evaluation via Stratified Cross-Validation & Rigorous Model Selection

We evaluate Decision Tree and KNN using **Stratified 5-Fold Cross-Validation**. Random Forest uses the same outer 5-fold evaluation, with an inner 5-fold `GridSearchCV` for hyperparameter tuning. Metrics are computed from held-out folds, and cumulative out-of-fold confusion matrices and ROC curves are displayed.

"""

# Outer CV for model evaluation
outer_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

models_dict = {
    "Decision Tree": dt_pipeline,
    "K-Nearest Neighbors": knn_pipeline,
    "Random Forest (Nested CV)": grid_search_rf
}

scoring_metrics = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']

nested_cv_results = []
oof_confusion_matrices = {}

for name, model in models_dict.items():
    cv_res = cross_validate(model, X, y, cv=outer_cv, scoring=scoring_metrics, n_jobs=1)

    oof_preds = cross_val_predict(model, X, y, cv=outer_cv, n_jobs=1)
    oof_probs = cross_val_predict(model, X, y, cv=outer_cv, method='predict_proba', n_jobs=1)[:, 1]

    cm = confusion_matrix(y, oof_preds)
    tn, fp, fn, tp = cm.ravel()
    oof_confusion_matrices[name] = (cm, oof_preds, oof_probs)

    nested_cv_results.append({
        "Model": name,
        "CV Mean Accuracy": f"{cv_res['test_accuracy'].mean():.4f} +/- {cv_res['test_accuracy'].std():.4f}",
        "CV Mean Precision": f"{cv_res['test_precision'].mean():.4f} +/- {cv_res['test_precision'].std():.4f}",
        "CV Mean Recall": f"{cv_res['test_recall'].mean():.4f} +/- {cv_res['test_recall'].std():.4f}",
        "CV Mean F1-Score": f"{cv_res['test_f1'].mean():.4f} +/- {cv_res['test_f1'].std():.4f}",
        "CV Mean ROC-AUC": f"{cv_res['test_roc_auc'].mean():.4f} +/- {cv_res['test_roc_auc'].std():.4f}",
        "TN": tn, "FP": fp, "FN": fn, "TP": tp
    })

nested_summary_df = pd.DataFrame(nested_cv_results)
print("--- Stratified 5-Fold Cross-Validation Summary Table (N = 330) ---")
display(nested_summary_df[["Model", "CV Mean Accuracy", "CV Mean Precision", "CV Mean Recall", "CV Mean F1-Score", "CV Mean ROC-AUC"]])

print("\n--- Out-of-Fold Cumulative Confusion Matrix Counts ---")
display(nested_summary_df[["Model", "TN", "FP", "FN", "TP"]])

"""### Simple Majority-Class Baseline

A `DummyClassifier` is included as a sanity-check baseline. It is **not one of the three coursework models**. Because 76.7% of the inpatient cohort belongs to the readmitted class, this baseline shows how much performance can be obtained simply by always predicting the majority class.
"""

# Simple majority-class baseline for comparison only
dummy_model = DummyClassifier(strategy='most_frequent')

dummy_cv = cross_validate(
    dummy_model, X, y, cv=outer_cv, scoring=scoring_metrics, n_jobs=1
)
dummy_oof_preds = cross_val_predict(dummy_model, X, y, cv=outer_cv, n_jobs=1)
dummy_cm = confusion_matrix(y, dummy_oof_preds)
dummy_tn, dummy_fp, dummy_fn, dummy_tp = dummy_cm.ravel()

print("--- Dummy Majority-Class Baseline ---")
print(f"Accuracy:  {dummy_cv['test_accuracy'].mean():.4f} +/- {dummy_cv['test_accuracy'].std():.4f}")
print(f"Precision: {dummy_cv['test_precision'].mean():.4f} +/- {dummy_cv['test_precision'].std():.4f}")
print(f"Recall:    {dummy_cv['test_recall'].mean():.4f} +/- {dummy_cv['test_recall'].std():.4f}")
print(f"F1-Score:  {dummy_cv['test_f1'].mean():.4f} +/- {dummy_cv['test_f1'].std():.4f}")
print(f"ROC-AUC:   {dummy_cv['test_roc_auc'].mean():.4f} +/- {dummy_cv['test_roc_auc'].std():.4f}")
print(f"Confusion Matrix Counts: TN={dummy_tn}, FP={dummy_fp}, FN={dummy_fn}, TP={dummy_tp}")

"""### Model 1 Out-of-Fold Confusion Matrix: Decision Tree"""

# Plot Decision Tree Confusion Matrix individually
fig, ax = plt.subplots(figsize=(5, 4))
dt_oof_preds = oof_confusion_matrices["Decision Tree"][1]
ConfusionMatrixDisplay.from_predictions(y, dt_oof_preds, ax=ax, cmap='Blues', colorbar=False)
ax.set_title("Decision Tree Out-of-Fold Confusion Matrix")
plt.tight_layout()
plt.show()

"""### Model 2 Out-of-Fold Confusion Matrix: K-Nearest Neighbors (KNN)"""

# Plot KNN Confusion Matrix individually
fig, ax = plt.subplots(figsize=(5, 4))
knn_oof_preds = oof_confusion_matrices["K-Nearest Neighbors"][1]
ConfusionMatrixDisplay.from_predictions(y, knn_oof_preds, ax=ax, cmap='Greens', colorbar=False)
ax.set_title("K-Nearest Neighbors Out-of-Fold Confusion Matrix")
plt.tight_layout()
plt.show()

"""### Model 3 Out-of-Fold Confusion Matrix: Random Forest (Optimized)"""

# Plot Random Forest Confusion Matrix individually
fig, ax = plt.subplots(figsize=(5, 4))
rf_oof_preds = oof_confusion_matrices["Random Forest (Nested CV)"][1]
ConfusionMatrixDisplay.from_predictions(y, rf_oof_preds, ax=ax, cmap='Oranges', colorbar=False)
ax.set_title("Random Forest Out-of-Fold Confusion Matrix")
plt.tight_layout()
plt.show()

"""### Comparative Receiver Operating Characteristic (ROC) Curves"""

# Plot Out-of-Fold ROC Curves individually
plt.figure(figsize=(8, 6))
ax = plt.gca()

for name, (_, _, oof_probs) in oof_confusion_matrices.items():
    RocCurveDisplay.from_predictions(y, oof_probs, name=name, ax=ax)

plt.title("Out-of-Fold Comparative Receiver Operating Characteristic (ROC) Curves")
plt.grid(True, alpha=0.3)
plt.show()

"""### Rigorous Model Selection Rationale

1. **Best among the three coursework models:** Random Forest has the highest mean Accuracy (**0.7636 ± 0.0074**), Recall (**0.9922 ± 0.0096**), F1-Score (**0.8655 ± 0.0043**), and ROC-AUC (**0.5726 ± 0.0540**). Decision Tree has marginally higher Precision (**0.7738**) than Random Forest (**0.7677**).
2. **Clinical sensitivity:** Random Forest produces only **2 false negatives** and **251 true positives** in the out-of-fold predictions, so it misses very few readmitted patients.
3. **Stability:** Random Forest has the smallest F1 fold-to-fold standard deviation (**0.0043**) among the three candidate models.
4. **Important baseline warning:** The majority-class `DummyClassifier` obtains approximately **0.7667 Accuracy**, **1.0000 Recall**, **0.8679 F1**, and **0.5000 ROC-AUC** by predicting almost every patient as readmitted. Therefore, the Random Forest is selected as the best of the three trained coursework models, but its low ROC-AUC and very low true-negative count show that its practical discrimination is weak.
5. **Literature comparison:** The Random Forest ROC-AUC (**0.5726**) is well below the **0.75–0.76 AUROC** reported for large deep-EHR models, and is closer to the weak discrimination range reported for traditional administrative readmission models.

"""

# Fit baseline Random Forest model on full dataset (N=1000)
drop_cols_raw = ['record_id', 'patient_id', 'appointment_date', 'no_show', 'disease_risk_level', TARGET]
X_raw = raw_df.drop(columns=drop_cols_raw)
y_raw = raw_df[TARGET]

num_cols_raw = X_raw.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols_raw = X_raw.select_dtypes(include=['object', 'string']).columns.tolist()

preprocessor_raw = ColumnTransformer([
    ('num', StandardScaler(), num_cols_raw),
    ('cat', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False), cat_cols_raw)
])

rf_base_pipeline = Pipeline([
    ('preprocessor', preprocessor_raw),
    ('selector', SelectPercentile(score_func=f_classif, percentile=80)),
    ('classifier', RandomForestClassifier(max_depth=6, n_estimators=50, random_state=RANDOM_STATE))
])

rf_base_pipeline.fit(X_raw, y_raw)

# Calculate Baseline Permutation Feature Importance (N=1000)
print("Calculating Baseline Permutation Feature Importance (Full Dataset N=1000)...")
res_base = permutation_importance(
    rf_base_pipeline, X_raw, y_raw, n_repeats=30, random_state=RANDOM_STATE, scoring='f1', n_jobs=1
)

sorted_idx_base = res_base.importances_mean.argsort()[::-1]
feature_names_raw = X_raw.columns.tolist()

# Plot Baseline Permutation Feature Importance (N=1000)
plt.figure(figsize=(10, 7))
top_indices_base = sorted_idx_base[:10]
plt.barh(
    [feature_names_raw[i] for i in top_indices_base][::-1],
    res_base.importances_mean[top_indices_base][::-1],
    xerr=res_base.importances_std[top_indices_base][::-1],
    color='teal'
)
plt.title("Baseline Top 10 Features (Full Dataset N=1000: 'admitted' Dominates)")
plt.xlabel("Decrease in F1 Score")
plt.tight_layout()
plt.show()

"""### 2. Refined Global Permutation Feature Importance (Discharged Inpatient Cohort, N=330)

*After restricting the cohort to discharged inpatients ($N=330$), the refined permutation-importance plot is driven by variables such as `lab_tests_count`, `cholesterol_mg_dl`, `waiting_days`, `medicine_charge_lkr`, `lab_charge_lkr`, `diagnosis`, `blood_sugar_mg_dl`, `total_bill_lkr`, `treatments_count`, and related clinical/service variables. This removes the artificial dominance of the `admitted` flag.*

"""

# Fit final tuned Random Forest model on full inpatient cohort for XAI and serialization
grid_search_rf.fit(X, y)
best_rf_pipeline = grid_search_rf.best_estimator_
print(f"Final Inpatient Random Forest Model Fitted. Best Parameters: {grid_search_rf.best_params_}")

# Calculate Refined Permutation Feature Importance on Inpatient Cohort (N=330)
print("Calculating Refined Permutation Feature Importance (Inpatient Cohort N=330)...")
feature_names = X.columns.tolist()

result = permutation_importance(
    best_rf_pipeline, X, y, n_repeats=30, random_state=RANDOM_STATE, scoring='f1', n_jobs=1
)

sorted_importances_idx = result.importances_mean.argsort()[::-1]

# Plot Refined Permutation Feature Importance (N=330)
plt.figure(figsize=(10, 7))
top_indices = sorted_importances_idx[:10]
plt.barh(
    [feature_names[i] for i in top_indices][::-1],
    result.importances_mean[top_indices][::-1],
    xerr=result.importances_std[top_indices][::-1],
    color='teal'
)
plt.title("Refined Top 10 Clinical Features (Discharged Inpatients N=330)")
plt.xlabel("Decrease in F1 Score")
plt.tight_layout()
plt.show()

"""### 3. SHAP Global Feature Impact Summary Plot (Lundberg & Lee, 2017)"""

# Transform features through preprocessor and selector for SHAP analysis
X_trans = best_rf_pipeline.named_steps['preprocessor'].transform(X)
selector = best_rf_pipeline.named_steps['selector']
X_sel = selector.transform(X_trans)

# Get selected feature names
all_feature_names = best_rf_pipeline.named_steps['preprocessor'].get_feature_names_out()
selected_feature_names = [all_feature_names[i] for i, s in enumerate(selector.get_support()) if s]

# Compute TreeSHAP values
rf_clf_model = best_rf_pipeline.named_steps['classifier']
explainer = shap.TreeExplainer(rf_clf_model)
shap_values = explainer.shap_values(X_sel)

# Handle multi-output SHAP array format
if isinstance(shap_values, list):
    shap_vals_class1 = shap_values[1]
elif len(shap_values.shape) == 3:
    shap_vals_class1 = shap_values[:, :, 1]
else:
    shap_vals_class1 = shap_values

print("SHAP values calculated successfully!")

# Plot SHAP Summary Plot individually
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_vals_class1, X_sel, feature_names=selected_feature_names, show=False)
plt.title("SHAP Global Feature Impact Summary Plot (Class 1: Readmitted)")
plt.tight_layout()
plt.show()

"""### 4. SHAP Local Feature Attribution for Individual Patient #1"""

# Plot Local SHAP Explanation for Patient #1 individually
patient_idx = 0
plt.figure(figsize=(10, 5))
shap.bar_plot(
    shap_vals_class1[patient_idx],
    feature_names=selected_feature_names,
    max_display=10,
    show=False
)
plt.title(f"SHAP Local Feature Attribution for Individual Patient #{patient_idx+1}")
plt.tight_layout()
plt.show()

"""### 5. Subgroup Fairness Evaluation

Fairness cannot be assumed merely by excluding demographic variables ("fairness through unawareness"). We evaluate subgroup fairness by disaggregating performance metrics across demographic subgroups (`Gender` and `Age Group`).
"""

eval_df = X.copy()
eval_df['y_true'] = y.values
eval_df['y_pred'] = rf_oof_preds

fairness_records = []

# Gender Subgroups
for gender in eval_df['gender'].unique():
    sub = eval_df[eval_df['gender'] == gender]
    acc = accuracy_score(sub['y_true'], sub['y_pred'])
    rec = recall_score(sub['y_true'], sub['y_pred'], zero_division=0)
    prec = precision_score(sub['y_true'], sub['y_pred'], zero_division=0)
    f1 = f1_score(sub['y_true'], sub['y_pred'], zero_division=0)
    fairness_records.append({
        "Attribute": "Gender",
        "Subgroup": gender,
        "Sample Count (N)": len(sub),
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1-Score": f1
    })

# Age Subgroups (<50 vs >=50)
eval_df['age_group'] = np.where(eval_df['age'] < 50, "Age < 50", "Age >= 50")
for age_grp in eval_df['age_group'].unique():
    sub = eval_df[eval_df['age_group'] == age_grp]
    acc = accuracy_score(sub['y_true'], sub['y_pred'])
    rec = recall_score(sub['y_true'], sub['y_pred'], zero_division=0)
    prec = precision_score(sub['y_true'], sub['y_pred'], zero_division=0)
    f1 = f1_score(sub['y_true'], sub['y_pred'], zero_division=0)
    fairness_records.append({
        "Attribute": "Age Group",
        "Subgroup": age_grp,
        "Sample Count (N)": len(sub),
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1-Score": f1
    })

fairness_df = pd.DataFrame(fairness_records)
print("--- Demographic Subgroup Fairness Performance Table ---")
display(fairness_df.round(4))

"""### Subgroup Fairness Discussion

- **Out-of-fold evaluation:** Subgroup metrics use the Random Forest out-of-fold predictions, so each patient is evaluated by a model that did not train on that patient's row.
- **Recall / sensitivity parity:** Recall is very high in all reported gender and age subgroups (approximately 0.99), so the model misses few readmitted patients in each subgroup.
- **Precision differences:** Small differences in precision are observed between subgroups. These differences may come from subgroup base rates and/or model behaviour, so they should not be treated as proof of either fairness or bias.
- **Important limitation:** High subgroup recall is partly caused by the model predicting the majority `readmitted` class very often. Fairness results must therefore be interpreted together with the low overall true-negative count and weak ROC-AUC.

### Ethical Considerations

- The SmartCare dataset is synthetic, so the model has **not** been clinically validated on real patients.
- False negatives could miss a patient who needs follow-up, while false positives could create unnecessary workload and anxiety.
- Demographic subgroup performance should be monitored because high overall performance does not automatically guarantee fairness.
- Real healthcare systems must protect patient privacy and use appropriate access controls for clinical data.
- The Streamlit application is an **educational decision-support prototype only**. It should support, not replace, qualified clinical judgement.

# Task 08 – AI Prototype Development (Streamlit Dashboard Setup)

We save the trained production pipeline and preprocessor for integration with the Streamlit app (`app.py`).

"""

# Save trained pipeline and preprocessor
joblib.dump(best_rf_pipeline, "best_readmission_rf_model.joblib")
joblib.dump(best_rf_pipeline.named_steps['preprocessor'], "readmission_preprocessor.joblib")
print("Saved production RandomForest pipeline successfully!")
print("Saved preprocessor pipeline successfully!")